Wolf
CSC207-UofT/lab-3-trader-tut5101-noname pull request #2
Opened 2021-09-27 23:37 UTC by georgewesley

I made a Wolf

2021-09-27 23:43 UTC, wBernie requested changes

2021-09-27 23:43 UTC, wBernie commented on src/main/java/Wolf.java
> +        //Is your wolf a little slow? Maybe they just don't like running? Well in that case, downgrade your wolf today!
javadocs aren't written like this and instead should be before the method using /**

2021-09-28 00:05 UTC, wBernie approved these changes

2021-09-28 00:06 UTC, georgewesley commented
Fixing Wolf

2021-09-28 00:07 UTC, merged