Cows
CSC207-UofT/lab-3-trader-tut5101-noname pull request #6
Opened 2021-09-27 23:45 UTC by logatsang

please

2021-09-27 23:52 UTC, edwardsues reviewed
See Reviews

2021-09-27 23:52 UTC, edwardsues commented on src/main/java/Cow.java
> +     * Feed the cow a fixed amount of feed, increasing its size.
should it be Starve the cow?

2021-09-27 23:52 UTC, edwardsues commented on src/main/java/Cow.java
> + * Cows are nice. I like cows because they are a funny animal.
unnecessary comments

2021-09-27 23:54 UTC, edwardsues requested changes
Check reviews concerning your documentation

2021-09-27 23:54 UTC, logatsang commented on src/main/java/Cow.java
> +     * Feed the cow a fixed amount of feed, increasing its size.
i  am sorry i am bad at 
programing

2021-09-27 23:54 UTC, logatsang commented on src/main/java/Cow.java
> + * Cows are nice. I like cows because they are a funny animal.
hn

2021-09-27 23:57 UTC, edwardsues commented on src/main/java/Cow.java
> + * Cows are nice. I like cows because they are a funny animal.
cry about it

2021-09-27 23:58 UTC, logatsang commented
please it  is good now p

2021-09-27 23:59 UTC, merged

2021-09-28 00:27 UTC, logatsang reviewed
y